//! Static curated op list.

use super::{OpSideEffect, OpSpec, OpSurface};
use serde_json::json;

#[allow(clippy::too_many_arguments)]
fn op(
    id: &str,
    cli: Option<&str>,
    mcp_tool: Option<&str>,
    summary: &str,
    side_effects: OpSideEffect,
    surfaces: &[OpSurface],
    requires_confirmation: bool,
    input: serde_json::Value,
    output: serde_json::Value,
    errors: &[&str],
    examples: &[&str],
) -> OpSpec {
    OpSpec {
        id: id.into(),
        cli: cli.map(str::to_string),
        mcp_tool: mcp_tool.map(str::to_string),
        summary: summary.into(),
        side_effects,
        surfaces: surfaces.to_vec(),
        supports_dry_run: false,
        requires_confirmation,
        input,
        output,
        errors: errors.iter().map(|s| (*s).to_string()).collect(),
        examples: examples.iter().map(|s| (*s).to_string()).collect(),
    }
}

pub fn build() -> Vec<OpSpec> {
    let cli = &[OpSurface::Cli];
    let both = &[OpSurface::Cli, OpSurface::Mcp];

    vec![
        op(
            "vault.create",
            Some("agentero vault create"),
            None,
            "Scaffold a vault (catalog, dirs, AGENTS.md, bundled skills).",
            OpSideEffect::Write,
            cli,
            false,
            json!({"path": "directory", "open?": "bool"}),
            json!({"path": "string", "created": ["rel…"], "updated": ["rel…"], "openPath": "string"}),
            &["io", "message"],
            &["agentero vault create ~/research --json"],
        ),
        op(
            "vault.list",
            Some("agentero vault list"),
            None,
            "List known vaults recorded by vault create.",
            OpSideEffect::Read,
            cli,
            false,
            json!({}),
            json!({"vaults": [{"path": "string", "exists": "bool", "default": "bool"}], "count": "number"}),
            &[],
            &["agentero vault list --json"],
        ),
        op(
            "paper.list",
            Some("agentero paper list"),
            Some("paper_list"),
            "L1 catalog index. Default JSON rows are id/path/title only; add fields or full for more.",
            OpSideEffect::Read,
            both,
            false,
            json!({
                "query?": "string",
                "tag?": ["string"],
                "unread?": "bool",
                "status?": "string (CLI)",
                "fields?": ["id|path|title|authors|year|date|tags|…"],
                "full?": "bool",
                "limit?": "number (MCP, default 50, max 200)"
            }),
            json!({"items": [{"id": "string", "path": "string", "title": "string"}]}),
            &["usage", "vault_not_found"],
            &[
                "agentero paper list --json",
                "agentero paper list --fields year,tags --json",
                "MCP paper_list { \"unread\": true, \"fields\": [\"year\", \"tags\"] }",
            ],
        ),
        op(
            "paper.get",
            Some("agentero paper get"),
            Some("paper_get"),
            "One paper's catalog metadata (includes abstract) plus asset hints on CLI.",
            OpSideEffect::Read,
            both,
            false,
            json!({"ref": "paper id or vault-relative path"}),
            json!({"id": "string", "path": "string", "title": "string", "abstract?": "string", "isRead": "bool"}),
            &["paper_not_found", "paper_ambiguous"],
            &["agentero paper get papers/1706.03762 --json"],
        ),
        op(
            "paper.paths",
            Some("agentero paper paths"),
            None,
            "Print related file paths for a paper (no body dump).",
            OpSideEffect::Read,
            cli,
            false,
            json!({"ref": "paper id or path"}),
            json!({"paths": ["string"]}),
            &["paper_not_found", "paper_ambiguous"],
            &["agentero paper paths papers/demo --json"],
        ),
        op(
            "paper.set_read",
            Some("agentero paper set-read"),
            Some("paper_set_read"),
            "Set catalog is_read (does not run paper-reader).",
            OpSideEffect::Write,
            both,
            false,
            json!({"ref": "paper id or path", "isRead?": "bool (MCP default true; CLI --false clears)"}),
            json!({"id": "string", "path": "string", "isRead": "bool"}),
            &["paper_not_found", "paper_ambiguous"],
            &[
                "agentero paper set-read papers/demo --json",
                "MCP paper_set_read { \"ref\": \"papers/demo\", \"isRead\": true }",
            ],
        ),
        op(
            "paper.tag.add",
            Some("agentero paper tag add"),
            Some("paper_tag_add"),
            "Add tags (optional color suffix topic:blue).",
            OpSideEffect::Write,
            both,
            false,
            json!({"ref": "paper id or path", "tags": ["string"]}),
            json!({"id": "string", "path": "string", "tags": ["string"]}),
            &["paper_not_found", "message"],
            &["agentero paper tag add papers/demo survey:blue --json"],
        ),
        op(
            "paper.tag.rm",
            Some("agentero paper tag rm"),
            Some("paper_tag_rm"),
            "Remove tags by name (case-insensitive).",
            OpSideEffect::Write,
            both,
            false,
            json!({"ref": "paper id or path", "tags": ["string"]}),
            json!({"id": "string", "path": "string", "tags": ["string"]}),
            &["paper_not_found", "message"],
            &["agentero paper tag rm papers/demo survey --json"],
        ),
        op(
            "paper.tag.set",
            Some("agentero paper tag set"),
            None,
            "Replace all tags (or --clear).",
            OpSideEffect::Write,
            cli,
            false,
            json!({"ref": "paper id or path", "tags": ["string"], "clear?": "bool"}),
            json!({"id": "string", "path": "string", "tags": ["string"]}),
            &["paper_not_found"],
            &["agentero paper tag set papers/demo nlp:green --json"],
        ),
        op(
            "paper.tag.list",
            Some("agentero paper tag list"),
            None,
            "Tag inventory across the catalog.",
            OpSideEffect::Read,
            cli,
            false,
            json!({"all?": "bool include @zotero:/@arxiv:"}),
            json!({"tags": [{"name": "string", "count": "number"}]}),
            &[],
            &["agentero paper tag list --json"],
        ),
        op(
            "paper.delete",
            Some("agentero paper delete"),
            None,
            "Move paper/org folder to recycle bin; --files permanently deletes (needs -y).",
            OpSideEffect::Destructive,
            cli,
            true,
            json!({"path": "vault-relative under papers/", "files?": "bool"}),
            json!({"path": "string", "trashed": "bool"}),
            &["needs_confirmation", "paper_not_found"],
            &["agentero paper delete papers/demo -y --json"],
        ),
        op(
            "paper.move",
            Some("agentero paper move"),
            None,
            "Move a paper or org folder under papers/ (supports cross-vault absolute paths).",
            OpSideEffect::Write,
            cli,
            false,
            json!({"from": "path", "to_parent": "path"}),
            json!({"from": "string", "to": "string"}),
            &["paper_not_found", "message"],
            &["agentero paper move papers/inbox/demo papers/archive --json"],
        ),
        op(
            "paper.download",
            Some("agentero paper download"),
            None,
            "Download PDF / arXiv TeX for an existing paper.",
            OpSideEffect::Write,
            cli,
            false,
            json!({"ref": "paper id or path"}),
            json!({"path": "string", "pdf": "bool", "tex": "bool"}),
            &["paper_not_found", "import_failed"],
            &["agentero paper download papers/demo --json"],
        ),
        op(
            "paper.parse",
            Some("agentero paper parse"),
            None,
            "LiteParse PDF → PAPER.md when no TeX (--force overwrites).",
            OpSideEffect::Write,
            cli,
            false,
            json!({"ref": "paper id or path", "force?": "bool"}),
            json!({"path": "string", "paperMd": "string"}),
            &["paper_not_found", "paper_pdf_missing", "message"],
            &["agentero paper parse papers/demo --json"],
        ),
        op(
            "import.id",
            Some("agentero import id"),
            Some("import_id"),
            "Magic-wand import by arXiv id / DOI / URL.",
            OpSideEffect::Write,
            both,
            false,
            json!({"text": "arxiv|doi|url", "parent?": "vault-relative under papers/ (default papers)"}),
            json!({"path": "string", "id": "string", "title": "string", "pdf": "bool", "tex": "bool", "paperMd": "bool"}),
            &["import_failed", "message"],
            &[
                "agentero import id 1706.03762 --json",
                "MCP import_id { \"text\": \"1706.03762\", \"parent\": \"papers/nlp\" }",
            ],
        ),
        op(
            "import.pdf",
            Some("agentero import pdf"),
            None,
            "Import local PDF file(s) into vault (copy + catalog + NOTES.md shell).",
            OpSideEffect::Write,
            cli,
            false,
            json!({"files": ["path…"], "parent?": "vault-relative under papers/ (default papers)"}),
            json!({
                "papers": [{"path": "string", "id": "string", "title": "string", "pdf": "bool", "tex": "bool", "paperMd": "bool"}],
                "errors": ["string"]
            }),
            &["import_failed", "message"],
            &[
                "agentero import pdf /path/to/paper.pdf --json",
                "agentero import pdf paper1.pdf paper2.pdf --parent papers/nlp --json",
            ],
        ),
        op(
            "export.bib",
            Some("agentero export bib"),
            None,
            "Export catalog as BibTeX (Translator).",
            OpSideEffect::Read,
            cli,
            false,
            json!({"format?": "string", "output?": "file path"}),
            json!({"format": "string", "content": "string", "count": "number", "writtenTo?": "string"}),
            &["export_failed"],
            &["agentero export bib --json"],
        ),
        op(
            "layout.list",
            Some("agentero layout list"),
            Some("layout_list"),
            "List sidebar layout regions (figures/tables/algorithms/formulas) from layout-index.json.",
            OpSideEffect::Read,
            both,
            false,
            json!({
                "ref": "paper id or path",
                "kind?": ["figure|image|chart|table|algorithm|formula"],
                "minScore?": "number 0-1"
            }),
            json!({
                "paperPath": "string",
                "indexPath": "string",
                "items": [{"id": "string", "kind": "string", "section": "string", "page": "number", "bbox": {"x":0,"y":0,"w":0,"h":0}, "score": "number"}]
            }),
            &["layout_index_missing", "layout_index_invalid", "paper_not_found", "usage"],
            &[
                "agentero layout list papers/demo --kind figure --json",
                "MCP layout_list { \"ref\": \"papers/demo\", \"kind\": [\"figure\"] }",
            ],
        ),
        op(
            "layout.get",
            Some("agentero layout get"),
            Some("layout_get"),
            "Get one layout region by id (e.g. figure-3).",
            OpSideEffect::Read,
            both,
            false,
            json!({"ref": "paper id or path", "id": "region id"}),
            json!({"paperPath": "string", "item": {"id": "string", "page": "number", "bbox": {"x":0,"y":0,"w":0,"h":0}}}),
            &["layout_index_missing", "layout_region_not_found", "paper_not_found"],
            &["agentero layout get papers/demo figure-3 --json"],
        ),
        op(
            "mark.list",
            Some("agentero mark list"),
            None,
            "List reading marks for a paper.",
            OpSideEffect::Read,
            cli,
            false,
            json!({"ref": "paper id or path"}),
            json!({"marks": [{"id": "string", "kind": "string"}]}),
            &["paper_not_found"],
            &["agentero mark list papers/demo --json"],
        ),
        op(
            "mark.add",
            Some("agentero mark add"),
            None,
            "Add highlight/批注/translate/ask via --quote, or region mark via --region (CLI resolves geometry).",
            OpSideEffect::Write,
            cli,
            false,
            json!({
                "ref": "paper id or path",
                "kind?": "highlight|translate|ask",
                "quote?": "verbatim sentence",
                "region?": "layout region id",
                "comment?": "string",
                "question?": "string",
                "page?": "number",
                "to?": "lang for translate"
            }),
            json!({"ids": ["string"], "count": "number", "path": "string"}),
            &["mark_locate_failed", "paper_pdf_missing", "layout_index_missing", "layout_region_not_found"],
            &[
                "agentero mark add papers/demo --kind highlight --quote \"…\" --json",
                "agentero mark add papers/demo --region figure-3 --comment \"…\" --json",
            ],
        ),
        op(
            "mark.get",
            Some("agentero mark get"),
            None,
            "Get one mark by id.",
            OpSideEffect::Read,
            cli,
            false,
            json!({"ref": "paper id or path", "id": "mark id"}),
            json!({"id": "string", "kind": "string"}),
            &["paper_not_found", "message"],
            &["agentero mark get papers/demo <id> --json"],
        ),
        op(
            "mark.update",
            Some("agentero mark update"),
            None,
            "Update mark comment / color.",
            OpSideEffect::Write,
            cli,
            false,
            json!({"ref": "paper id or path", "id": "mark id", "comment?": "string", "markColor?": "string"}),
            json!({"id": "string"}),
            &["paper_not_found", "message"],
            &["agentero mark update papers/demo <id> --comment \"…\" --json"],
        ),
        op(
            "mark.delete",
            Some("agentero mark delete"),
            None,
            "Delete a mark (needs -y under --json / non-TTY).",
            OpSideEffect::Destructive,
            cli,
            true,
            json!({"ref": "paper id or path", "id": "mark id"}),
            json!({"id": "string", "deleted": "bool"}),
            &["needs_confirmation", "paper_not_found"],
            &["agentero mark delete papers/demo <id> -y --json"],
        ),
        op(
            "translate",
            Some("agentero translate"),
            None,
            "Free machine translation of plain text (no API key; no mark written).",
            OpSideEffect::Read,
            cli,
            false,
            json!({"text": "string", "to?": "lang", "from?": "lang", "provider?": "id"}),
            json!({"text": "string", "translated": "string", "provider": "string"}),
            &["message", "usage"],
            &["agentero translate \"Hello\" --to zh-CN --json"],
        ),
        op(
            "doctor",
            Some("agentero doctor"),
            None,
            "Aggregate vault/catalog/wikilink/alias/marks diagnostics.",
            OpSideEffect::Read,
            cli,
            false,
            json!({}),
            json!({"ok": "bool", "issues": ["…"]}),
            &["doctor_issues"],
            &["agentero doctor --json"],
        ),
        op(
            "doctor.wiki",
            Some("agentero doctor wiki"),
            None,
            "Check wikilinks (optional vault-relative file/dir scope).",
            OpSideEffect::Read,
            cli,
            false,
            json!({"source?": "vault-relative md file or directory"}),
            json!({"checkedFiles": "number", "counts": {"resolved":0,"missing":0,"ambiguous":0,"invalidFragment":0}, "issues": ["…"]}),
            &["wikilink_check_failed", "usage"],
            &["agentero doctor wiki papers/demo/NOTES.md --json"],
        ),
        op(
            "paper.notes.get",
            None,
            Some("paper_notes_get"),
            "Read NOTES.md for a paper (MCP). Empty string if missing.",
            OpSideEffect::Read,
            &[OpSurface::Mcp],
            false,
            json!({"ref": "paper id or path"}),
            json!({"ref": "string", "id": "string", "content": "string"}),
            &["paper_not_found"],
            &["MCP paper_notes_get { \"ref\": \"papers/demo\" }"],
        ),
        op(
            "paper.notes.write",
            None,
            Some("paper_notes_write"),
            "Write NOTES.md (replace or append). Confirm with user before replace of user notes.",
            OpSideEffect::Write,
            &[OpSurface::Mcp],
            false,
            json!({"ref": "paper id or path", "content": "string", "mode?": "replace|append"}),
            json!({"ref": "string", "id": "string", "mode": "string"}),
            &["paper_not_found", "message"],
            &["MCP paper_notes_write { \"ref\": \"papers/demo\", \"content\": \"# Notes\\n\", \"mode\": \"append\" }"],
        ),
        op(
            "file.list",
            None,
            Some("file_list"),
            "List one vault directory (MCP). Empty path is the vault root. Skips .agentero and LaTeX build artifacts.",
            OpSideEffect::Read,
            &[OpSurface::Mcp],
            false,
            json!({"path?": "vault-relative directory", "limit?": "1–500, default 200"}),
            json!({"path": "string", "entries": [{"name": "string", "path": "string", "kind": "file|directory"}], "truncated": "bool"}),
            &["message"],
            &["MCP file_list { \"path\": \"drafts\" }"],
        ),
        op(
            "file.read",
            None,
            Some("file_read"),
            "Read one UTF-8 vault text file (MCP), including drafts outside papers/.",
            OpSideEffect::Read,
            &[OpSurface::Mcp],
            false,
            json!({"path": "vault-relative file"}),
            json!({"path": "string", "content": "string", "bytes": "number"}),
            &["message"],
            &["MCP file_read { \"path\": \"drafts/main.tex\" }"],
        ),
        op(
            "file.write",
            None,
            Some("file_write"),
            "Write one UTF-8 vault text file (replace or append). Confirm before replace. Not NOTES.md.",
            OpSideEffect::Write,
            &[OpSurface::Mcp],
            false,
            json!({"path": "vault-relative file", "content": "string", "mode?": "replace|append"}),
            json!({"path": "string", "mode": "string", "bytes": "number"}),
            &["message"],
            &["MCP file_write { \"path\": \"drafts/main.tex\", \"content\": \"\\\\section{A}\\n\", \"mode\": \"append\" }"],
        ),
        op(
            "open",
            Some("agentero open"),
            None,
            "Open a local directory as a Vault in the desktop App (deep link).",
            OpSideEffect::None,
            cli,
            false,
            json!({"path": "directory"}),
            json!({"path": "string", "methods": ["string"]}),
            &["message"],
            &["agentero open ~/research --json"],
        ),
        op(
            "describe",
            Some("agentero describe"),
            None,
            "Introspect curated ops (this catalog). Omit id for the index.",
            OpSideEffect::None,
            cli,
            false,
            json!({"op?": "op id or mcp tool name"}),
            json!({"ops": [{"id": "string", "summary": "string"}]}),
            &["usage"],
            &["agentero describe --json", "agentero describe paper.list --json"],
        ),
    ]
}
