export { getPdfAiRuntime } from "@/lib/pdf/layout/ai-runtime";
export {
	LAYOUT_KIND_BADGE_CLASS,
	LAYOUT_KIND_BORDER,
	LAYOUT_KIND_FILL,
	LAYOUT_KIND_HEX,
	layoutKindBorder,
	layoutKindFill,
	layoutKindHex,
} from "@/lib/pdf/layout/colors";
export {
	LAYOUT_FORMULA_HOVER_DWELL_MS,
	LAYOUT_FORMULA_HOVER_HIDE_MS,
	LAYOUT_HOVER_DWELL_MS,
	LAYOUT_HOVER_HIDE_MS,
	LAYOUT_SIDEBAR_MIN_SCORE,
} from "@/lib/pdf/layout/constants";
export {
	bboxContainment,
	bboxIoU,
	type DedupeLayoutOptions,
	dedupeLayoutRegions,
} from "@/lib/pdf/layout/dedupe";
export { enqueuePaperLayoutAnalysis } from "@/lib/pdf/layout/enqueue-paper-layout";
export {
	analyzePaperLayoutHeadless,
	type HeadlessLayoutResult,
} from "@/lib/pdf/layout/headless-analyze";
export {
	bboxArea,
	hoverableLayoutRegions,
	hoverableLayoutRegionsByPage,
	hoverableLayoutRegionsOnPage,
	pickLayoutRegionAtPoint,
	pointInBbox,
	rawLayoutRegionsByPage,
	rawLayoutRegionsOnPage,
} from "@/lib/pdf/layout/hit-test";
export {
	LAYOUT_INDEX_FILE,
	LAYOUT_SIDECAR_FILE,
	LAYOUT_SIDECAR_SCHEMA_VERSION,
	layoutIndexPath,
	layoutSidecarPath,
	type PdfLayoutSidecar,
	parseLayoutSidecar,
	readLayoutIndex,
	readLayoutSidecar,
	writeLayoutIndex,
	writeLayoutIndexFromRaw,
	writeLayoutSidecar,
} from "@/lib/pdf/layout/io";
export {
	isAlgorithmLayoutKind,
	isCaptionLayoutKind,
	isFigureLayoutKind,
	isFormulaLayoutKind,
	isFormulaNumberLayoutKind,
	isLayoutBodyTextKind,
	isLayoutTranslatableKind,
	isLayoutTranslateHeadingKind,
	isSidebarLayoutKind,
	isTableLayoutKind,
	isTargetLayoutLabel,
	isTextLayoutKind,
	layoutDedupeGroup,
	layoutKindI18nKey,
	layoutLabelToKind,
} from "@/lib/pdf/layout/labels";
export {
	buildLayoutIndexItems,
	buildLayoutIndexSidecar,
	LAYOUT_INDEX_SCHEMA_VERSION,
	type LayoutIndexBbox,
	type LayoutIndexItem,
	type LayoutIndexKind,
	type LayoutIndexSection,
	type LayoutIndexSidecar,
	parseLayoutIndexSidecar,
	slugFromTitle,
} from "@/lib/pdf/layout/layout-index";
export {
	groupLayoutTranslateItemsByPage,
	LAYOUT_TRANSLATE_CONCURRENCY,
	LAYOUT_TRANSLATE_MAX_CHARS,
	type LayoutTranslateItem,
	type LayoutTranslateItemStatus,
	type LayoutTranslateJobStatus,
	type LayoutTranslateRegion,
	layoutRegionSourceText,
	listTranslatableLayoutRegions,
	runLayoutRegionTranslate,
	toLayoutTranslateItems,
} from "@/lib/pdf/layout/layout-translate";
export {
	areFigureNeighbors,
	bboxCoveredBy,
	bboxFullyContains,
	buildFigureBboxWithFullTitle,
	type CaptionPlacement,
	captionAttachScore,
	captionCompatibleWithHost,
	clipFigureBboxToTitleColumn,
	compareLayoutReadingOrder,
	connectedPanelGroups,
	formulaSortAnchor,
	hostFamily,
	isMainAlgorithmCaption,
	isMainFigureCaption,
	isMainTableCaption,
	isSubpanelCaption,
	LAYOUT_MERGE,
	type LayoutHostFamily,
	layoutReadingColumn,
	mergeCaptionsIntoHosts,
	mergeFormulasByNumber,
	panelInTitleColumn,
	panelsAboveTitle,
	preferredCaptionPlacement,
	requireFigureTitles,
	resolveFigureBboxOverlaps,
	selectClusterForTitle,
	selectFormulasForNumber,
	suppressOrphanFiguresInsideClusters,
	suppressSpuriousFigureDetections,
	unionBbox,
	verticalCeilingForTitle,
} from "@/lib/pdf/layout/merge-captions";
export {
	attachLayoutModelTaskListener,
	ensureLayoutModel,
	getLayoutModelStatus,
	LAYOUT_MODEL_TASK_ID,
	type LayoutModelStatus,
	layoutModelLocalUrl,
	prefetchLayoutModel,
} from "@/lib/pdf/layout/model";
export {
	buildLayoutDocumentResult,
	documentLayoutToResult,
	pageLayoutToRegions,
	regionsFromDocumentLayout,
	summarizeLayoutResult,
} from "@/lib/pdf/layout/normalize";
export {
	type RunLayoutAnalysisOptions,
	runDocumentLayoutAnalysis,
} from "@/lib/pdf/layout/run-analysis";
export {
	clearLayoutDocumentResult,
	getFocusedLayoutRegion,
	getLayoutDocumentResult,
	isLayoutOverlayVisible,
	layoutAnalysisStore,
	setFocusedLayoutRegion,
	setLayoutAnalysisUi,
	setLayoutDocumentResult,
	setLayoutOverlayVisible,
	toggleLayoutOverlayVisible,
} from "@/lib/pdf/layout/store";
export {
	attachTitlesFromTextRuns,
	type CaptionRole,
	captionRoleFromGeometry,
	captionRoleFromText,
	enrichCaptionRegionsWithText,
	looksLikeFigureCaption,
	resolveCaptionRole,
	textFromRunsInBbox,
} from "@/lib/pdf/layout/title-text";
export type {
	LayoutAnalysisUiStatus,
	PdfLayoutDocumentResult,
	PdfLayoutKind,
	PdfLayoutRegion,
} from "@/lib/pdf/layout/types";
